export const CATEGORY_IMAGES = {
    "10380": "//www.cbmro.com/resources/processed_150/hlr-system/category image/high level/206769_300[1].png",
    "10408": "//www.cbmro.com/resources/processed_150/hlr-system/category image/1top categories/trb-e2-07_opt.png",
    "10934": "//www.cbmro.com/resources/processed_150/hlr-system/category image/1top categories/mseal.png",
    "10364": "//www.cbmro.com/resources/processed_150/hlr-system/category image/process equipments/400-500_series_high_pressure_lg.png",
    "10488": "//www.cbmro.com/resources/processed_150/hlr-system/category image/hydraulic/images.png",
    "10358": "//www.cbmro.com/resources/processed_150/hlr-system/category image/tools/hand tools/wrench/040212672.png",
    "10421": "//www.cbmro.com/resources/processed_150/hlr-system/category image/belting/belting.png",
    "10377": "//www.cbmro.com/resources/processed_150/hlr-system/category image/1top categories/bolts.png",
    "10774": "//www.cbmro.com/resources/processed_150/hlr-system/category image/tools/cutting tools/cutting tools.png",
    "10452": "//www.cbmro.com/resources/processed_150/hlr-system/category image/high level/safety_helmet.png",
    "10627": "//www.cbmro.com/resources/processed_150/hlr-system/category image/high level/p_al_bl74_401g[1].png",
    "10384": "//www.cbmro.com/resources/processed_150/hlr-system/category image/linears/profile rail guide.png",
    "10433": "//www.cbmro.com/resources/processed_150/hlr-system/category image/hardware/spring2.png",
    "10368": "//www.cbmro.com/resources/processed_150/hlr-system/category image/high level/main_image_brooms[1].png",
    "10425": "//www.cbmro.com/resources/processed_150/hlr-system/category image/high level/high_pressure_oil_can.png",
    "10390": "//www.cbmro.com/resources/processed_150/hlr-system/category image/high level/loctite_243_lg[1].png",
    "10415": "//www.cbmro.com/resources/processed_150/hlr-system/category image/electrical/plugs (electrical).png",
    "10761": "//www.cbmro.com/resources/processed_150/hlr-system/category image/motors/baldorsuper-e.png",
    "10589": "//www.cbmro.com/resources/processed_150/hlr-system/category image/1top categories/flapwheel.png",
    "11117": "//www.cbmro.com/resources/processed_150/hlr-system/category image/1top categories/shoot-and-inhale-welding-torch-h01-12-.png",
    "10446": "//www.cbmro.com/resources/processed_150/hlr-system/category image/high level/ss-3068294-laboratorybeaker[1].png",
    "10849": "//www.cbmro.com/resources/processed_150/hlr-system/category image/1top categories/service-bell-icon.png",
    "default": "/placeholder.png"
};
